version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./api:/api
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
    hostname: mid.dena.software
  php:
    build: ./api
    volumes:
      - ./api:/api
    networks:
      - code-network
    hostname: mid.dena.software
  app:
    build:
      context: ./app/
    volumes:
      - ./app/:/usr/app
      - /usr/app/node_modules
    ports:
      - '80:3000'
    # https://github.com/facebook/create-react-app/issues/8688
    # because of react-scripts is v3.2 so it will cause the `exit with code 0 error` when npm start
    # add below code would solve the problem
    stdin_open: true
    hostname: mid.dena.software
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: myDb
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - code-network
    hostname: mid.dena.software
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8082:80
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - code-network
    hostname: mid.dena.software
networks:
  code-network:
    driver: bridge
